<?php

/**
 * @file
 * Contains rsvp_form.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rsvp_form_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rsvp_form module.
    case 'help.page.rsvp_form':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a RSVP block for your events') . '</p>';
      return $output;

    default:
  }
}
